'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
const empty=()=>({version:1,circuitStandard:'itc-bt-25-v1',walls:[],openings:[],background:null,circuits:makeCircuits(),elements:[],ignitionLinks:[]});
let project=empty(),past=[],future=[],tool='wall',selected=null,anchor=null,hover=null,drag=null,space=false,image=null,scale=65,offset={x:80,y:80};
const copy=x=>JSON.parse(JSON.stringify(x)),message=t=>$('status').textContent=t;
function snapshot(){past.push(copy(project));if(past.length>80)past.shift();future=[]}
function restore(p){project=copy(p);project.circuits??=makeCircuits();project.elements??=[];for(const element of project.elements)if(element.type==='cgp')element.type='panel';project.ignitionLinks??=[];ignitionDraft=null;ignitionStart=null;updateIgnitionButton();syncCircuits();selected=null;anchor=null;image=null;$('imageWidth').value=p.background?.width||10;$('opacity').value=p.background?.opacity??.35;if(p.background){const img=new Image();img.onload=()=>{if(project.background?.data===img.src){image=img;render()}};img.src=p.background.data}render()}
const length=w=>Math.hypot(w.b.x-w.a.x,w.b.y-w.a.y);
function point(e,snap=true){const r=canvas.getBoundingClientRect();let p={x:(e.clientX-r.left-offset.x)/scale,y:(e.clientY-r.top-offset.y)/scale};if(snap&&$('snap').checked){p.x=Math.round(p.x*10)/10;p.y=Math.round(p.y*10)/10}return p}
function projection(w,p){const dx=w.b.x-w.a.x,dy=w.b.y-w.a.y;return Math.max(0,Math.min(1,((p.x-w.a.x)*dx+(p.y-w.a.y)*dy)/(dx*dx+dy*dy)))}
function nearest(p){let best=null;for(const w of project.walls){const t=projection(w,p),d=Math.hypot(p.x-w.a.x-t*(w.b.x-w.a.x),p.y-w.a.y-t*(w.b.y-w.a.y));if(d<Math.max(18/scale,w.thickness/2)&&(!best||d<best.d))best={w,t,d}}return best}
function wallSnap(p,exclude){const radius=Math.max(.12,14/scale);let best=null;for(const w of project.walls){if(w.id===exclude)continue;for(const end of [w.a,w.b]){const d=Math.hypot(p.x-end.x,p.y-end.y);if(d<=radius&&(!best||d<best.d))best={x:end.x,y:end.y,d,endpoint:true}}}if(best)return {x:best.x,y:best.y};for(const w of project.walls){if(w.id===exclude)continue;const t=projection(w,p),q={x:w.a.x+(w.b.x-w.a.x)*t,y:w.a.y+(w.b.y-w.a.y)*t},d=Math.hypot(p.x-q.x,p.y-q.y);if(d<=radius&&(!best||d<best.d))best={...q,d}}return best?{x:best.x,y:best.y}:p}
function wallEndpoint(w,p){const radius=Math.max(.14,16/scale),da=Math.hypot(p.x-w.a.x,p.y-w.a.y),db=Math.hypot(p.x-w.b.x,p.y-w.b.y);return Math.min(da,db)<=radius?(da<=db?'a':'b'):null}
function moveJoinedEndpoints(original,current,from,to,skip){const epsilon=1e-6;for(const wall of current.walls){if(wall.id===skip)continue;const old=original.walls.find(item=>item.id===wall.id);if(!old)continue;for(const end of ['a','b'])if(Math.hypot(old[end].x-from.x,old[end].y-from.y)<epsilon)wall[end]={...to}}}
function wallOpeningsFit(w){const l=length(w);return l>.05&&project.openings.filter(o=>o.wall===w.id).every(o=>o.t*l>=o.width/2-1e-6&&(1-o.t)*l>=o.width/2-1e-6)}
function joinedEndpointsFit(original,from,to,skip){const epsilon=1e-6;return original.walls.every(wall=>{if(wall.id===skip)return true;const candidate=copy(wall);for(const end of ['a','b'])if(Math.hypot(wall[end].x-from.x,wall[end].y-from.y)<epsilon)candidate[end]={...to};return wallOpeningsFit(candidate)})}
function position(o){const w=project.walls.find(w=>w.id===o.wall);return {x:w.a.x+(w.b.x-w.a.x)*o.t,y:w.a.y+(w.b.y-w.a.y)*o.t}}
function hit(p){const electrical=hitElectrical(p);if(electrical)return electrical;const ignition=hitIgnition(p);if(ignition)return ignition;for(const o of [...project.openings].reverse()){const w=project.walls.find(w=>w.id===o.wall),q=position(o),l=length(w),ux=(w.b.x-w.a.x)/l,uy=(w.b.y-w.a.y)/l,dx=p.x-q.x,dy=p.y-q.y,x=dx*ux+dy*uy,y=(-dx*uy+dy*ux)*(o.flip?-1:1),pad=12/scale;const gap=Math.abs(x)<=o.width/2+pad&&Math.abs(y)<=Math.max(w.thickness/2,pad);const leaf=o.type==='door'&&Math.abs(x+o.width/2)<=pad&&y>=-pad&&y<=o.width+pad;const arc=o.type==='door'&&x>=-o.width/2-pad&&y>=-pad&&Math.abs(Math.hypot(x+o.width/2,y)-o.width)<=pad;if(gap||leaf||arc)return {kind:'opening',id:o.id}}const n=nearest(p);return n?{kind:'wall',id:n.w.id}:null}
function available(w,t,width,ignore){const l=length(w);return t*l>=width/2-1e-6&&(1-t)*l>=width/2-1e-6&&!project.openings.some(o=>o.wall===w.id&&o.id!==ignore&&Math.abs(o.t-t)*l<(o.width+width)/2-.001)}
function line(a,b,color,width){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
function render(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle='#f4f6fa';ctx.fillRect(0,0,r.width,r.height);ctx.translate(offset.x,offset.y);ctx.scale(scale,scale);
if(image&&project.background){ctx.globalAlpha=project.background.opacity;ctx.drawImage(image,0,0,project.background.width,project.background.width*image.height/image.width);ctx.globalAlpha=1}
const step=scale<40?1:.1;ctx.strokeStyle='#dce3ed';ctx.lineWidth=1/scale;ctx.beginPath();for(let x=Math.ceil(-offset.x/scale/step)*step;x<(r.width-offset.x)/scale;x+=step){ctx.moveTo(x,-offset.y/scale);ctx.lineTo(x,(r.height-offset.y)/scale)}for(let y=Math.ceil(-offset.y/scale/step)*step;y<(r.height-offset.y)/scale;y+=step){ctx.moveTo(-offset.x/scale,y);ctx.lineTo((r.width-offset.x)/scale,y)}ctx.stroke();
ctx.save();ctx.lineCap='round';for(const w of project.walls){line(w.a,w.b,selected?.id===w.id?'#00a86b':'#334155',w.thickness);ctx.fillStyle='#334155';ctx.font=`${12/scale}px system-ui`;ctx.textAlign='center';ctx.fillText(length(w).toFixed(2)+' m',(w.a.x+w.b.x)/2,(w.a.y+w.b.y)/2-12/scale);if(selected?.kind==='wall'&&selected.id===w.id){for(const end of [w.a,w.b]){ctx.beginPath();ctx.arc(end.x,end.y,7/scale,0,2*Math.PI);ctx.fillStyle='#fff';ctx.fill();ctx.lineWidth=2/scale;ctx.strokeStyle='#00a86b';ctx.stroke()}}}ctx.restore();
for(const o of project.openings){const w=project.walls.find(w=>w.id===o.wall),p=position(o);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(w.b.y-w.a.y,w.b.x-w.a.x));ctx.fillStyle='#f4f6fa';ctx.fillRect(-o.width/2,-w.thickness/2-.005,o.width,w.thickness+.01);const color=selected?.id===o.id?'#00a86b':o.type==='door'?'#a16207':'#0284c7';ctx.strokeStyle=color;ctx.lineWidth=2/scale;if(o.type==='window'){ctx.strokeRect(-o.width/2,-w.thickness/2,o.width,w.thickness);line({x:-o.width/2,y:0},{x:o.width/2,y:0},color,2/scale)}else{ctx.scale(1,o.flip?-1:1);line({x:-o.width/2,y:0},{x:-o.width/2,y:o.width},color,2/scale);ctx.beginPath();ctx.arc(-o.width/2,0,o.width,0,Math.PI/2);ctx.stroke()}ctx.restore()}
drawElectrical();if(anchor&&hover){line(anchor,hover,'#00a86b',Math.max(.05,Math.min(.6,Number($('thickness').value)/100||.15)));const text=Math.hypot(hover.x-anchor.x,hover.y-anchor.y).toFixed(2)+' m',x=(anchor.x+hover.x)/2,y=(anchor.y+hover.y)/2-16/scale;ctx.font=`${14/scale}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';const width=ctx.measureText(text).width+16/scale;ctx.fillStyle='#ffffff';ctx.fillRect(x-width/2,y-11/scale,width,22/scale);ctx.fillStyle='#007b50';ctx.fillText(text,x,y);ctx.textBaseline='alphabetic';}}
function choose(t){if(ignitionDraft&&t==='select'){ignitionDraft=null;ignitionStart=null;updateIgnitionButton()}else if(ignitionDraft&&t!=='ignition'){ignitionBusy();return}finish();ignitionStart=null;tool=t;canvas.style.cursor=t==='pan'?'grab':'default';anchor=null;selected=null;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));message(t==='ignition'?'Selecciona el primer element de la connexió d’encesa.':t==='pan'?'Arrossega el plànol per desplaçar la vista.':t==='wall'?'Marca el primer extrem de la paret.':t==='select'?'Selecciona una paret. Arrossega un extrem per allargar-la o el tram per moure-la.':'Fes clic sobre una paret.');refreshElectricalTools();render()}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>choose(b.dataset.tool));
canvas.onpointerdown=e=>{if(e.button!==0&&e.button!==1)return;canvas.setPointerCapture(e.pointerId);if(tool==='pan'||space||e.button===1){drag={pan:true,x:e.clientX,y:e.clientY,offset:{...offset}};return}let p=point(e);if(tool==='ignition'){ignitionClick(point(e,false));render();return}if(tool.startsWith('electric:')){placeElectrical(tool.slice(9),p);render();return}if(tool==='wall'){p=wallSnap(p);if(!anchor){anchor=p;hover=p;message('Marca el segon extrem.')}else if(Math.hypot(p.x-anchor.x,p.y-anchor.y)>.05){snapshot();project.walls.push({id:crypto.randomUUID(),a:anchor,b:p,thickness:Math.max(.05,Math.min(.6,Number($('thickness').value)/100||.15))});anchor=null;message('Paret creada i ajustada. Marca el primer extrem de la següent.')}}else if(tool==='select'){selected=hit(point(e,false));if(selected){const wall=selected.kind==='wall'&&project.walls.find(w=>w.id===selected.id),wallEnd=wall?wallEndpoint(wall,point(e,false)):null;drag=selected.kind==='ignition'?null:{p,original:copy(project),changed:false,wallEnd};message(selected.kind==='ignition'?'Encesa seleccionada. Elimina per treure el grup.':selected.kind==='element'?'Arrossega l’element elèctric per moure’l.':selected.kind==='opening'?'Arrossega l’obertura al llarg de la paret. Porta: botó Canvia obertura o doble clic.':wallEnd?'Arrossega aquest extrem per modificar o allargar la paret.':'Arrossega el tram per moure tota la paret.');}}else{const n=nearest(p),width=Number($('width').value)/100;if(!n){message('Cal fer clic sobre una paret.');return}if(!Number.isFinite(width)||width<.3||width>4){message('Indica una amplada entre 30 i 400 cm.');return}const half=width/(2*length(n.w)),t=Math.max(half,Math.min(1-half,n.t));if(!available(n.w,t,width)){message('No hi ha prou espai lliure en aquesta paret.');return}snapshot();const id=crypto.randomUUID();project.openings.push({id,wall:n.w.id,type:tool,t,width,flip:false});choose('select');selected={kind:'opening',id};message('Obertura creada i seleccionada. Arrossega-la per moure-la.')}render()};
canvas.onpointermove=e=>{hover=point(e);if(anchor)hover=wallSnap(hover);if(drag?.pan){offset={x:drag.offset.x+e.clientX-drag.x,y:drag.offset.y+e.clientY-drag.y}}else if(drag&&selected){const dx=hover.x-drag.p.x,dy=hover.y-drag.p.y;if(selected.kind==='element'){const element=project.elements.find(e=>e.id===selected.id),original=drag.original.elements.find(e=>e.id===selected.id);element.x=original.x+dx;element.y=original.y+dy;drag.changed=dx!==0||dy!==0;}else if(selected.kind==='wall'){const w=project.walls.find(w=>w.id===selected.id),orig=drag.original.walls.find(w=>w.id===selected.id);if(drag.wallEnd){const target=wallSnap({x:orig[drag.wallEnd].x+dx,y:orig[drag.wallEnd].y+dy},w.id),candidate={...w,[drag.wallEnd]:target};if(wallOpeningsFit(candidate)&&joinedEndpointsFit(drag.original,orig[drag.wallEnd],target,w.id)){w[drag.wallEnd]=target;moveJoinedEndpoints(drag.original,project,orig[drag.wallEnd],target,w.id);drag.changed=target.x!==orig[drag.wallEnd].x||target.y!==orig[drag.wallEnd].y}}else{const nextA={x:orig.a.x+dx,y:orig.a.y+dy},nextB={x:orig.b.x+dx,y:orig.b.y+dy};if(joinedEndpointsFit(drag.original,orig.a,nextA,w.id)&&joinedEndpointsFit(drag.original,orig.b,nextB,w.id)){w.a=nextA;w.b=nextB;moveJoinedEndpoints(drag.original,project,orig.a,w.a,w.id);moveJoinedEndpoints(drag.original,project,orig.b,w.b,w.id);drag.changed=dx!==0||dy!==0;}}}else{const o=project.openings.find(o=>o.id===selected.id),w=project.walls.find(w=>w.id===o.wall),original=drag.original.openings.find(x=>x.id===o.id),center=position(original),half=o.width/(2*length(w)),t=Math.max(half,Math.min(1-half,projection(w,{x:center.x+dx,y:center.y+dy})));if(available(w,t,o.width,o.id)){o.t=t;drag.changed=o.t!==drag.original.openings.find(x=>x.id===o.id).t}}}render()};
function finish(){if(drag&&!drag.pan&&drag.changed){past.push(drag.original);if(past.length>80)past.shift();future=[]}drag=null}canvas.onpointerup=finish;canvas.onpointercancel=finish;
function zoom(f,x=canvas.clientWidth/2,y=canvas.clientHeight/2){const next=Math.max(15,Math.min(300,scale*f));offset={x:x-(x-offset.x)*next/scale,y:y-(y-offset.y)*next/scale};scale=next;render()}
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoom(e.deltaY<0?1.1:1/1.1,e.clientX-r.left,e.clientY-r.top)},{passive:false});$('plus').onclick=()=>zoom(1.2);$('minus').onclick=()=>zoom(1/1.2);$('center').onclick=()=>{const points=[...project.walls.flatMap(w=>[w.a,w.b]),...project.elements.filter(elementVisible).map(e=>({x:e.x,y:e.y}))];if(project.background)points.push({x:0,y:0},{x:project.background.width,y:project.background.width*(image?image.height/image.width:1)});if(!points.length){scale=65;offset={x:80,y:80}}else{const xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);scale=Math.max(15,Math.min(150,(canvas.clientWidth-100)/Math.max(1,maxX-minX),(canvas.clientHeight-100)/Math.max(1,maxY-minY)));offset={x:canvas.clientWidth/2-(minX+maxX)*scale/2,y:canvas.clientHeight/2-(minY+maxY)*scale/2}}render()};
$('undo').onclick=()=>{if(ignitionDraft){ignitionDraft.members.pop();message(ignitionDraft.members.length+' element(s) seleccionats.');render();return}finish();if(past.length){future.push(copy(project));restore(past.pop())}};$('redo').onclick=()=>{if(ignitionBusy())return;finish();if(future.length){past.push(copy(project));restore(future.pop())}};
$('remove').onclick=()=>{if(ignitionBusy())return;if(!selected)return;snapshot();if(selected.kind==='wall'){project.walls=project.walls.filter(w=>w.id!==selected.id);project.openings=project.openings.filter(o=>o.wall!==selected.id)}else if(selected.kind==='element'){project.elements=project.elements.filter(e=>e.id!==selected.id);project.ignitionLinks=project.ignitionLinks.filter(link=>link.a!==selected.id&&link.b!==selected.id)}else if(selected.kind==='ignition'){const target=project.ignitionLinks.find(link=>link.id===selected.id);project.ignitionLinks=project.ignitionLinks.filter(link=>target?.ignition?link.ignition!==target.ignition:link.id!==selected.id);}else project.openings=project.openings.filter(o=>o.id!==selected.id);selected=null;render()};$('flip').onclick=()=>{const o=project.openings.find(o=>o.id===selected?.id);if(o?.type==='door'){snapshot();o.flip=!o.flip;render()}else message('Selecciona una porta per canviar el sentit d’obertura.')};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&ignitionDraft){e.preventDefault();cancelIgnition();return}if(/INPUT|TEXTAREA|BUTTON/.test(e.target.tagName))return;if(e.code==='Space'){space=true;e.preventDefault()}if(e.key==='Escape'){if(ignitionDraft)return;ignitionStart=null;if(drag&&!drag.pan)restore(drag.original);drag=null;anchor=null;render()}if(e.key==='Delete')$('remove').click();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$(e.shiftKey?'redo':'undo').click()}});document.addEventListener('keyup',e=>{if(e.code==='Space')space=false});window.addEventListener('blur',()=>{space=false;finish()});
$('image').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>12e6){message('La imatge ha de pesar menys de 12 MB.');return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{snapshot();image=img;project.background={data:reader.result,width:Math.max(.1,Math.min(1000,Number($('imageWidth').value)||10)),opacity:Number($('opacity').value)};render()};img.onerror=()=>message('No s’ha pogut obrir la imatge.');img.src=reader.result};reader.readAsDataURL(f);e.target.value=''};
$('imageWidth').onchange=()=>{const n=Number($('imageWidth').value);if(project.background&&n>=.1&&n<=1000){snapshot();project.background.width=n;render()}};$('opacity').onchange=()=>{if(project.background){snapshot();project.background.opacity=Number($('opacity').value);render()}};$('clearImage').onclick=()=>{if(project.background){snapshot();project.background=null;image=null;render()}};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('save').onclick=()=>{if(ignitionBusy())return;finish();download(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),'thoseplant.json');message('Projecte exportat. Conserva el fitxer per continuar més endavant.')};$('load').onclick=()=>{if(!ignitionBusy())$('file').click()};
function validate(p){const finite=q=>q&&Number.isFinite(q.x)&&Number.isFinite(q.y)&&Math.abs(q.x)<10000&&Math.abs(q.y)<10000;if(!p||p.version!==1||!Array.isArray(p.walls)||!Array.isArray(p.openings)||p.walls.length>5000||p.openings.length>5000||(!validElectrical(p)||!validIgnition(p)))return false;const ids=new Set();for(const w of p.walls){if(typeof w.id!=='string'||ids.has(w.id)||!finite(w.a)||!finite(w.b)||!Number.isFinite(w.thickness)||w.thickness<.05||w.thickness>.6||length(w)<.05)return false;ids.add(w.id)}const oids=new Set();for(const o of p.openings){const w=p.walls.find(w=>w.id===o.wall);if(!w||typeof o.id!=='string'||ids.has(o.id)||oids.has(o.id)||!['door','window'].includes(o.type)||typeof o.flip!=='boolean'||!Number.isFinite(o.t)||!Number.isFinite(o.width)||o.width<.3||o.width>4)return false;const l=length(w);if(o.t*l<o.width/2-1e-6||(1-o.t)*l<o.width/2-1e-6||p.openings.some(q=>q!==o&&q.wall===o.wall&&Math.abs(q.t-o.t)*l<(q.width+o.width)/2-.001))return false;oids.add(o.id)}const b=p.background;return b===null||(b&&typeof b.data==='string'&&/^data:image\/(png|jpeg|webp);base64,/.test(b.data)&&b.data.length<17000000&&Number.isFinite(b.width)&&b.width>=.1&&b.width<=1000&&Number.isFinite(b.opacity)&&b.opacity>=0&&b.opacity<=1)}
$('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>20e6)throw Error();const p=JSON.parse(await f.text());if(Array.isArray(p.elements))for(const element of p.elements)if(element.type==='cgp')element.type='panel';if(!validate(p))throw Error();snapshot();restore(p);message('Projecte carregat.')}catch{message('Projecte no vàlid. El plànol actual es conserva.')}finally{e.target.value=''}};
$('png').onclick=()=>{const saved=selected;selected=null;render();canvas.toBlob(b=>{if(b)download(b,'thoseplant.png')});selected=saved;render();message('S’exporta la vista actual. Centra el plànol abans d’exportar-lo.')};$('new').onclick=()=>{if(ignitionBusy())return;if((project.walls.length||project.elements.length||project.background)&&!confirm('Vols començar un plànol nou? Desa el projecte si el vols conservar.'))return;snapshot();restore(empty());message('Plànol nou. Marca el primer extrem de la paret.')};
new ResizeObserver(render).observe($('area'));render();

function setPanel(open){document.body.classList.toggle('panel-closed',!open);$('togglePanel').setAttribute('aria-expanded',String(open));$('togglePanel').textContent='Amaga Menú lateral';$('showPanel').setAttribute('aria-expanded',String(open));$('showPanel').hidden=open;}
setPanel(true);
$('togglePanel').onclick=()=>setPanel(document.body.classList.contains('panel-closed'));
canvas.addEventListener('dblclick',e=>{if(tool!=='select')return;const target=hit(point(e,false));if(target?.kind==='opening'&&project.openings.find(o=>o.id===target.id)?.type==='door'){selected=target;$('flip').click();}});

initializeElectrical();
initializeSchematics();

initializeIgnition();

$('rotateElement').onclick=()=>{if(ignitionBusy())return;if(selected?.kind==='element'){snapshot();const element=project.elements.find(e=>e.id===selected.id);element.rotation=((element.rotation||0)+90)%360;render()}else if(selected?.kind==='opening'&&project.openings.find(o=>o.id===selected.id)?.type==='door')$('flip').click();else message('Selecciona un símbol elèctric o una porta per girar-lo.');};

$('showPanel').onclick=()=>{setPanel(true);$('togglePanel').focus()};
