/* Local-only project state; animation and view state are never serialized. */
(()=>{
 'use strict';const T=ThosMotion,M=T.model,C=T.connections,$=id=>document.getElementById(id),canvas=$('canvas'),world=$('world'),renderer=new T.renderer.Renderer(world),KEY='thosmotion:last-project:v1';
 let project=M.empty(),selected=null,solution,angles=new Map(),running=false,panMode=false,drag=null,hover=null,pendingBelt=null,last=0,view={x:0,y:0,scale:2},past=[],future=[];
 const status=s=>$('status').textContent=s;
 const clone=p=>structuredClone(p);
 const serialize=()=>JSON.stringify(project,null,2);
 function backup(){try{localStorage.setItem(KEY,serialize());$('recover').hidden=false;}catch{status('No es pot desar la recuperació local. Pots descarregar el fitxer amb Desa.');}}
 function pause(){running=false;$('play').textContent='▶ Simula';}
 function refresh(resetAngles=true){C.revalidate(project);solution=T.solver.solve(project);if(resetAngles)angles=T.renderer.phases(project);renderer.rebuild(project,selected,solution,angles);world.setAttribute('transform',`translate(${view.x} ${view.y}) scale(${view.scale})`);$('zoom').textContent=`${Math.round(view.scale*100)}%`;$('welcome').hidden=!!project.components.length;$('undo').disabled=!past.length;$('redo').disabled=!future.length;inspect();status(solution.diagnostics.map(d=>d.message).join(' ')||`${project.connections.length} connexions validades · ${running?'Simulació':'En pausa'}`);}
 // Bounded snapshots are appropriate for this small prototype (maximum 200 components).
 function commit(before){if(JSON.stringify(before)===JSON.stringify(project)){refresh(false);return;}past.push(before);if(past.length>80)past.shift();future=[];backup();refresh();}
 function edit(fn){pause();const before=clone(project);fn();commit(before);}
 function history(from,to){if(!from.length)return;pause();to.push(clone(project));project=from.pop();selected=null;backup();refresh();}
 function point(e){const box=canvas.getBoundingClientRect();return {x:(e.clientX-box.left-view.x)/view.scale,y:(e.clientY-box.top-view.y)/view.scale};}
 const current=()=>project.components.find(c=>c.id===selected);
 function info(c){const s=solution.states.get(c.id),n=s.rpm,detail=c.type==='gear'?` · Z = ${c.properties.teeth}`:c.type==='pulley'?` · D = ${c.properties.diameter} mm`:'';return `${M.library[c.type].label}${detail}\nn = ${n.toLocaleString('ca',{maximumFractionDigits:3})} rpm\nω = ${M.rpmToRad(n).toLocaleString('ca',{maximumFractionDigits:3})} rad/s\n${s.conflict?'Bloquejat':n>0?'Antihorari':n<0?'Horari':'Aturat'}${s.ratio?`\ni acumulada = ${Math.abs(1/s.ratio).toLocaleString('ca',{maximumFractionDigits:3})}`:''}`;}
 function inspect(){const c=current();$('inspector').hidden=!c;if(!c)return;$('name').textContent=M.library[c.type].label;$('fields').replaceChildren();
  function field(label,key,min,max,step){const row=document.createElement('label');row.append(document.createTextNode(label));const input=document.createElement('input');input.type='number';Object.assign(input,{min,max,step,value:c.properties[key]});input.onchange=()=>{const v=Number(input.value);if(!input.checkValidity()||!Number.isFinite(v)){input.value=c.properties[key];return;}const count=project.connections.length;edit(()=>c.properties[key]=v);if(project.connections.length<count)status('El canvi ha trencat una connexió: torna a apropar els components per connectar-los.');};row.append(input);$('fields').append(row);}
  if(c.type==='gear'){field('Dents','teeth',8,120,1);field('Mòdul (mm)','module',.5,5,.5);}else if(c.type==='pulley')field('Diàmetre (mm)','diameter',10,240,1);else if(c.type==='motor'){field('Velocitat (rpm)','rpm',-600,600,1);const row=document.createElement('label');row.textContent='Motor actiu';const check=document.createElement('input');check.type='checkbox';check.checked=c.properties.active;check.onchange=()=>edit(()=>c.properties.active=check.checked);row.append(check);$('fields').append(row);}
  $('values').textContent=info(c);$('values').style.whiteSpace='pre-line';$('disconnect').disabled=!project.connections.some(e=>e.a===c.id||e.b===c.id);
 }
 function fit(){if(!project.components.length){view={x:canvas.clientWidth/2,y:canvas.clientHeight/2,scale:2};refresh(false);return;}const xs=project.components.map(c=>c.position.x-M.radius(c)-25),ys=project.components.map(c=>c.position.y-M.radius(c)-25);const minX=Math.min(...xs),minY=Math.min(...ys),maxX=Math.max(...project.components.map(c=>c.position.x+M.radius(c)+25)),maxY=Math.max(...project.components.map(c=>c.position.y+M.radius(c)+45));view.scale=Math.max(.3,Math.min(3,(canvas.clientWidth-100)/(maxX-minX),(canvas.clientHeight-100)/(maxY-minY)));view.x=canvas.clientWidth/2-(minX+maxX)/2*view.scale;view.y=canvas.clientHeight/2-(minY+maxY)/2*view.scale;refresh(false);}
 document.querySelectorAll('[data-add]').forEach(btn=>btn.onclick=()=>{if(project.components.length>=M.MAX_COMPONENTS){status('Límit de 200 components.');return;}edit(()=>{const c=M.create(btn.dataset.add,(canvas.clientWidth/2-view.x)/view.scale,(canvas.clientHeight/2-view.y)/view.scale);project.components.push(c);selected=c.id;});});
 $('example').onchange=()=>{const kind=$('example').value;if(!kind)return;edit(()=>{project=M.empty();pendingBelt=null;if(kind==='compound'){const motor=M.create('motor',0,0),shaftA=M.create('shaft',0,0),g1=M.create('gear',0,0),shaftB=M.create('shaft',60,0),g2=M.create('gear',60,0),g3=M.create('gear',60,0),shaftC=M.create('shaft',120,0),g4=M.create('gear',120,0);motor.properties.rpm=100;g1.properties.teeth=20;g2.properties.teeth=40;g3.properties.teeth=10;g4.properties.teeth=50;project.components=[motor,shaftA,g1,shaftB,g2,g3,shaftC,g4];for(const c of project.components)C.snap(project,c);selected=g4.id;}else if(kind.startsWith('belt-')){const motor=M.create('motor',0,0),a=M.create('pulley',0,0),b=M.create('pulley',130,0);a.properties.diameter=80;b.properties.diameter=40;project.components=[motor,a,b];C.snap(project,motor);project.connections.push({id:crypto.randomUUID(),type:'belt',a:a.id,b:b.id,crossed:kind==='belt-crossed'});selected=b.id;}else{const ratio=kind==='reducer'?2:kind==='equal'?1:.5,motor=M.create('motor',0,0),a=M.create('gear',0,0),b=M.create('gear',20+20*ratio,0);b.properties.teeth=20*ratio;project.components=[motor,a,b];C.snap(project,a);C.snap(project,b);selected=b.id;}});$('example').value='';fit();};
 $('new').onclick=()=>{edit(()=>{project=M.empty();selected=null;pendingBelt=null;});fit();};$('undo').onclick=()=>history(past,future);$('redo').onclick=()=>history(future,past);
 $('delete').onclick=()=>{if(!current())return;edit(()=>{project.components=project.components.filter(c=>c.id!==selected);project.connections=project.connections.filter(e=>e.a!==selected&&e.b!==selected);selected=null;});};
 $('duplicate').onclick=()=>{const c=current();if(!c||project.components.length>=M.MAX_COMPONENTS)return;edit(()=>{const copy=clone(c);copy.id=crypto.randomUUID();copy.position.x+=M.radius(c)*2+15;project.components.push(copy);selected=copy.id;});};
 $('disconnect').onclick=()=>edit(()=>project.connections=project.connections.filter(e=>e.a!==selected&&e.b!==selected));$('close').onclick=()=>{selected=null;refresh(false);};
 $('play').onclick=()=>{running=!running;$('play').textContent=running?'Ⅱ Pausa':'▶ Simula';status(running?'Simulació en marxa':'En pausa');};$('reset').onclick=()=>{pause();refresh();};
 function advance(dt){for(const [id,s]of solution.states)angles.set(id,(angles.get(id)||0)+M.rpmToRad(s.rpm)*dt);renderer.animate(angles);}
 $('step').onclick=()=>{pause();advance(1/60);};$('fit').onclick=fit;$('pan').onclick=()=>{panMode=!panMode;$('pan').setAttribute('aria-pressed',panMode);};$('help').onclick=()=>$('helpBox').hidden=!$('helpBox').hidden;
 function startBelt(crossed){const c=current();if(!c||c.type!=='pulley'){status('Selecciona primer una politja.');return;}pendingBelt={first:c.id,crossed};status(`Clica la segona politja per crear una corretja ${crossed?'creuada':'oberta'}.`);}
 $('beltOpen').onclick=()=>startBelt(false);$('beltCrossed').onclick=()=>startBelt(true);
 canvas.onpointerdown=e=>{if(e.button!==0&&e.button!==1)return;const id=e.target.closest('[data-id]')?.dataset.id,c=project.components.find(c=>c.id===id);$('tooltip').hidden=true;if(pendingBelt&&e.button===0){const first=project.components.find(x=>x.id===pendingBelt.first);if(!c||c.type!=='pulley'){status('La corretja només pot acabar en una altra politja.');return;}if(c===first){status('Selecciona una segona politja diferent.');return;}if(C.distance(first,c)<=M.radius(first)+M.radius(c)){status('Les politges se superposen: separa-les abans de connectar-les.');return;}const existing=project.connections.some(x=>x.type==='belt'&&((x.a===first.id&&x.b===c.id)||(x.a===c.id&&x.b===first.id)));if(existing){status('Aquestes politges ja tenen una corretja.');pendingBelt=null;return;}const before=clone(project),crossed=pendingBelt.crossed;project.connections.push({id:crypto.randomUUID(),type:'belt',a:first.id,b:c.id,crossed});pendingBelt=null;selected=c.id;commit(before);status(`Corretja ${crossed?'creuada':'oberta'} creada.`);return;}canvas.setPointerCapture(e.pointerId);if(c&&!panMode&&e.button===0){pause();selected=id;drag={kind:'component',before:clone(project),c,start:point(e),origin:{...c.position}};refresh(false);}else{selected=null;drag={kind:'pan',x:e.clientX,y:e.clientY,origin:{...view}};refresh(false);}};
 canvas.onpointermove=e=>{if(drag){if(drag.kind==='pan'){view.x=drag.origin.x+e.clientX-drag.x;view.y=drag.origin.y+e.clientY-drag.y;world.setAttribute('transform',`translate(${view.x} ${view.y}) scale(${view.scale})`);}else{const p=point(e);drag.c.position={x:Math.max(-100000,Math.min(100000,drag.origin.x+p.x-drag.start.x)),y:Math.max(-100000,Math.min(100000,drag.origin.y+p.y-drag.start.y))};const relations=project.components.filter(c=>c!==drag.c).map(c=>C.relation(drag.c,c));refresh(false);if(relations.some(r=>r.state==='INTERFERENCE'))status('Les peces interfereixen. Apropa els cercles primitius fins al contacte.');else if(relations.some(r=>r.state==='VALID_CONTACT'))status('Contacte compatible: deixa anar per connectar.');}return;}
  const id=e.target.closest('[data-id]')?.dataset.id,c=project.components.find(c=>c.id===id);hover=c;$('tooltip').hidden=!c;if(c){$('tooltip').textContent=info(c);const box=canvas.getBoundingClientRect();$('tooltip').style.left=Math.min(e.clientX-box.left+15,canvas.clientWidth-245)+'px';$('tooltip').style.top=Math.min(e.clientY-box.top+15,canvas.clientHeight-150)+'px';}};
 function finish(cancel=false){if(!drag)return;const action=drag;drag=null;if(action.kind==='component'){if(cancel){project=action.before;refresh();}else{C.snap(project,action.c);commit(action.before);}}}
 canvas.onpointerup=()=>finish();canvas.onpointercancel=()=>finish(true);canvas.onpointerleave=()=>{$('tooltip').hidden=true;hover=null;};
 canvas.addEventListener('wheel',e=>{e.preventDefault();const p=point(e),box=canvas.getBoundingClientRect();view.scale=Math.max(.3,Math.min(6,view.scale*Math.exp(-e.deltaY*.001)));view.x=e.clientX-box.left-p.x*view.scale;view.y=e.clientY-box.top-p.y*view.scale;refresh(false);},{passive:false});
 document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();history(e.shiftKey?future:past,e.shiftKey?past:future);}else if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();history(future,past);}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();$('delete').click();}else if(e.key==='Escape'){finish(true);pendingBelt=null;selected=null;refresh(false);}else if(e.key.startsWith('Arrow')&&current()){e.preventDefault();const c=current();edit(()=>{c.position.x+=e.key==='ArrowRight'?2:e.key==='ArrowLeft'?-2:0;c.position.y+=e.key==='ArrowDown'?2:e.key==='ArrowUp'?-2:0;});}});
 $('save').onclick=()=>{const url=URL.createObjectURL(new Blob([serialize()],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='thosmotion.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 function load(data){const valid=M.validate(data);edit(()=>{project=valid;selected=null;});fit();}
 $('open').onclick=()=>$('file').click();$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>2000000)throw Error('El fitxer supera el límit de 2 MB.');load(JSON.parse(await f.text()));}catch(e){status(e.message);}finally{$('file').value='';}};
 $('recover').onclick=()=>{try{const text=localStorage.getItem(KEY);if(text)load(JSON.parse(text));}catch(e){status(e.message);}};
 try{$('recover').hidden=!localStorage.getItem(KEY);}catch{}
 function frame(now){if(running)advance(Math.min((now-last)/1000,.05)*Number($('speed').value));last=now;requestAnimationFrame(frame);}fit();requestAnimationFrame(frame);new ResizeObserver(()=>{if(!drag)refresh(false);}).observe(canvas);
})();
