(function(root){
 'use strict';const M=root.ThosMotion.model,NS='http://www.w3.org/2000/svg';
 const el=(tag,attrs={},parent)=>{const n=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(parent)parent.append(n);return n;};
 const overlap=(a,b,pad=0)=>a.x<b.x+b.width+pad&&a.x+a.width+pad>b.x&&a.y<b.y+b.height+pad&&a.y+a.height+pad>b.y;
 function layoutAnnotations(items){const placed=[],result=new Map(),componentBoxes=items.map(item=>({id:item.id,x:item.x-item.halfWidth-2,y:item.y-item.halfHeight-2,width:item.halfWidth*2+4,height:item.halfHeight*2+4}));for(const item of items){const width=Math.max(34,Math.min(72,Math.max(...item.lines.map(line=>line.length))*4.4+10)),height=21,w=item.halfWidth,h=item.halfHeight,raw=[{x:item.x-width/2,y:item.y+h+4},{x:item.x-width/2,y:item.y-h-height-4},{x:item.x+w+4,y:item.y-height/2},{x:item.x-w-width-4,y:item.y-height/2},{x:item.x+w+4,y:item.y+h+4},{x:item.x-w-width-4,y:item.y+h+4},{x:item.x+w+4,y:item.y-h-height-4},{x:item.x-w-width-4,y:item.y-h-height-4}];for(let lane=1;lane<=items.length+4;lane++)raw.push({x:item.x-width/2,y:item.y+h+4+lane*(height+3)});const candidates=raw.map(box=>({...box,width,height})),box=candidates.find(candidate=>!componentBoxes.some(other=>other.id!==item.id&&overlap(candidate,other,2))&&!placed.some(other=>overlap(candidate,other,2)))||candidates.at(-1);placed.push(box);result.set(item.id,box);}return result;}
 function gearPath(c){const z=c.properties.teeth,r=M.radius(c),m=c.properties.module;let d='';for(let i=0;i<z*4;i++){const a=(i+.5)*Math.PI*2/(z*4),rr=i%4===0||i%4===3?r-m*.8:r+m*.8;d+=`${i?'L':'M'}${rr*Math.cos(a)},${rr*Math.sin(a)} `;}return d+'Z';}
 function phases(p){const out=new Map(),map=new Map(p.components.map(c=>[c.id,c]));for(const source of [...p.components.filter(c=>c.type==='motor'),...p.components]){if(out.has(source.id))continue;out.set(source.id,source.type==='rack'?0:source.rotation);const queue=[source.id];for(let i=0;i<queue.length;i++){const a=map.get(queue[i]);for(const e of p.connections){const id=e.a===a.id?e.b:e.b===a.id?e.a:null;if(!id||out.has(id))continue;const b=map.get(id);if(!b)continue;const r=root.ThosMotion.connections.relation(a,b),valid=e.type==='belt'?a.type==='pulley'&&b.type==='pulley':r.state==='VALID_CONTACT';if(!valid)continue;let angle=out.get(a.id);if(e.type==='mesh'){const phi=Math.atan2(-(b.position.y-a.position.y),b.position.x-a.position.x);angle=((a.properties.teeth+b.properties.teeth)*phi+Math.PI*b.properties.teeth-Math.PI-a.properties.teeth*angle)/b.properties.teeth;}else if(e.type==='belt')angle*=root.ThosMotion.connections.ratio(e,a,b);else if(e.type==='rack')angle=b.type==='rack'?0:b.rotation;out.set(id,angle);queue.push(id);}}}return out;}
 function drawRack(c,parent,selected){const length=M.rackLength(c),half=length/2,pitch=Math.PI*c.properties.module,tooth=Math.max(2.2,c.properties.module*1.4),body=Math.max(1.4,c.properties.module*.7),clipId=`rack-clip-${c.id}`;el('rect',{x:-half,y:-body,width:length,height:body*2,rx:1.5,fill:selected?'#17434a':'#273643',stroke:'#91a9ba','stroke-width':1},parent);const clip=el('clipPath',{id:clipId},parent);el('rect',{x:-half,y:-tooth-1,width:length,height:(tooth+1)*2},clip);const teeth=el('g',{'clip-path':`url(#${clipId})`},parent);for(let x=-half-pitch;x<half+pitch;x+=pitch)el('path',{d:`M${x-pitch*.34},${-body} L${x},${-tooth} L${x+pitch*.34},${-body} M${x-pitch*.34},${body} L${x},${tooth} L${x+pitch*.34},${body}`,fill:'none',stroke:'#91a9ba','stroke-width':Math.max(.8,c.properties.module*.55),'stroke-linejoin':'round'},teeth);el('line',{x1:-half,y1:0,x2:half,y2:0,stroke:'#5e7485','stroke-width':.6,'stroke-dasharray':'3 3'},parent);return {teeth,pitch};}
 function drawCrankSlider(c,parent,rotor,selected){const r=c.properties.crankRadius,l=c.properties.rodLength;el('line',{x1:-r-8,y1:0,x2:r+l+14,y2:0,stroke:'#526b7c','stroke-width':2,'stroke-dasharray':'5 4'},parent);const rod=el('line',{stroke:'#91a9ba','stroke-width':5,'stroke-linecap':'round'},parent),slider=el('g',{},parent);el('rect',{x:-10,y:-8,width:20,height:16,rx:3,fill:selected?'#17434a':'#273643',stroke:'#91a9ba','stroke-width':2},slider);el('circle',{r:3.2,fill:'#111922',stroke:'#91a9ba'},slider);el('circle',{r:r+3,fill:selected?'#17434a':'#202d38',stroke:'#657d8e','stroke-width':1.5},rotor);el('line',{x1:0,y1:0,x2:r,y2:0,stroke:'#19b6bd','stroke-width':5,'stroke-linecap':'round'},rotor);el('circle',{cx:r,cy:0,r:4,fill:'#111922',stroke:'#91a9ba','stroke-width':1.5},rotor);parent.append(rotor);return {rod,slider,component:c};}
 function drawCamFollower(c,parent,rotor,selected){const r=c.properties.baseRadius,e=c.properties.eccentricity,top=-r-e-38;el('line',{x1:0,y1:top,x2:0,y2:-r+4,stroke:'#526b7c','stroke-width':2,'stroke-dasharray':'5 4'},parent);const follower=el('g',{},parent);el('line',{x1:0,y1:-30,x2:0,y2:-5,stroke:'#91a9ba','stroke-width':5,'stroke-linecap':'round'},follower);el('rect',{x:-9,y:-35,width:18,height:12,rx:2,fill:selected?'#17434a':'#273643',stroke:'#91a9ba','stroke-width':1.5},follower);el('circle',{cy:0,r:5,fill:'#202d38',stroke:'#91a9ba','stroke-width':1.5},follower);el('circle',{cx:e,cy:0,r,fill:selected?'#17434a':'#273643',stroke:'#91a9ba','stroke-width':2},rotor);el('line',{x1:0,y1:0,x2:e,y2:0,stroke:'#19b6bd','stroke-width':2.5},rotor);el('circle',{r:4,fill:'#111922',stroke:'#91a9ba'},rotor);parent.append(rotor);return {follower,component:c};}
 function beltLines(a,b,crossed){const dx=b.position.x-a.position.x,dy=b.position.y-a.position.y,d=Math.hypot(dx,dy)||1,px=-dy/d,py=dx/d,ra=M.radius(a),rb=M.radius(b),sign=crossed?-1:1;return [[a.position.x+px*ra,a.position.y+py*ra,b.position.x+px*rb*sign,b.position.y+py*rb*sign],[a.position.x-px*ra,a.position.y-py*ra,b.position.x-px*rb*sign,b.position.y-py*rb*sign]];}
 class Renderer{
   constructor(world){this.world=world;this.nodes=new Map();this.belts=[];}
  rebuild(p,selected,solution,angles){this.world.replaceChildren();this.nodes.clear();this.belts=[];const map=new Map(p.components.map(c=>[c.id,c])),visuals=new Map(p.components.map(c=>{const mount=c.type==='motor'?p.connections.find(e=>e.type==='shaft'&&(e.a===c.id||e.b===c.id)):null,partner=mount?map.get(mount.a===c.id?mount.b:mount.a):null,offset=partner?-(M.radius(partner)+45):0,bounds=M.bounds(c),anchorX=c.position.x+offset,anchorY=c.position.y,s=solution.states.get(c.id),dimension=c.type==='gear'?`Z${c.properties.teeth}`:c.type==='pulley'?`Ø${c.properties.diameter}`:c.type==='rack'?`Z${c.properties.teeth} · m${c.properties.module}`:c.type==='crankSlider'?`R${c.properties.crankRadius} · L${c.properties.rodLength}`:c.type==='camFollower'?`R${c.properties.baseRadius} · e${c.properties.eccentricity}`:M.library[c.type].label,speed=s.motion==='linear'?`${s.linearSpeed.toLocaleString('ca',{maximumFractionDigits:1})} mm/s`:`${s.rpm.toLocaleString('ca',{maximumFractionDigits:1})} rpm`;return [c.id,{id:c.id,x:anchorX+bounds.offsetX,y:anchorY+bounds.offsetY,anchorX,anchorY,offset,...bounds,lines:[dimension,speed]}];})),labels=layoutAnnotations([...visuals.values()]);for(const e of p.connections){const a=map.get(e.a),b=map.get(e.b);if(!a||!b)continue;if(e.type==='belt'){for(const [x1,y1,x2,y2]of beltLines(a,b,e.crossed)){const line=el('line',{x1,y1,x2,y2,stroke:'#7f95a6','stroke-width':4,'stroke-linecap':'round','stroke-dasharray':'5 3'},this.world);this.belts.push({line,id:e.a,direction:e.crossed?-1:1});}}else el('line',{x1:a.position.x,y1:a.position.y,x2:b.position.x,y2:b.position.y,stroke:'#526b7c','stroke-width':e.type==='shaft'?5:1.5,'stroke-dasharray':e.type==='mesh'?'3 4':'none'},this.world);}
    for(const c of p.components){const r=M.radius(c),visual=visuals.get(c.id),bounds=M.bounds(c),s=solution.states.get(c.id),offset=visual.offset;if(offset)el('line',{x1:c.position.x,y1:c.position.y,x2:c.position.x+offset,y2:c.position.y,stroke:'#087c87','stroke-width':2,'stroke-dasharray':'3 3'},this.world);const g=el('g',{'data-id':c.id,class:'component',tabindex:0,role:'button','aria-label':M.library[c.type].label,transform:`translate(${visual.anchorX} ${visual.anchorY})`},this.world);
    if(['rack','crankSlider','camFollower'].includes(c.type))el('rect',{x:bounds.offsetX-bounds.halfWidth-5,y:bounds.offsetY-bounds.halfHeight-5,width:(bounds.halfWidth+5)*2,height:(bounds.halfHeight+5)*2,rx:4,fill:'transparent',stroke:selected===c.id?'#087c87':s.conflict?'#b54238':'transparent','stroke-width':2,'pointer-events':'none',class:'halo'},g);else el('circle',{r:r+7,fill:'transparent',stroke:selected===c.id?'#087c87':s.conflict?'#b54238':'transparent','stroke-width':2,'pointer-events':'none',class:'halo'},g);
    const rotor=el('g',{},g);let rackAnimation=null,crankAnimation=null,camAnimation=null;if(c.type==='gear'){el('path',{d:gearPath(c),fill:selected===c.id?'#17434a':'#273643',stroke:'#91a9ba','stroke-width':1},rotor);el('circle',{r,fill:'none',stroke:'#5e7485','stroke-width':.6,'stroke-dasharray':'2 3'},rotor);}else if(c.type==='pulley'){el('circle',{r,fill:selected===c.id?'#17434a':'#202d38',stroke:'#91a9ba','stroke-width':3},rotor);el('circle',{r:r-5,fill:'none',stroke:'#657d8e','stroke-width':2},rotor);for(let i=0;i<4;i++)el('line',{x1:5,y1:0,x2:r-6,y2:0,stroke:'#71889a','stroke-width':2,transform:`rotate(${i*90})`},rotor);}else if(c.type==='rack')rackAnimation=drawRack(c,rotor,selected===c.id);else if(c.type==='crankSlider')crankAnimation=drawCrankSlider(c,g,rotor,selected===c.id);else if(c.type==='camFollower')camAnimation=drawCamFollower(c,g,rotor,selected===c.id);else if(c.type==='motor'){el('circle',{r,fill:'#087c87',stroke:'#00a8ad','stroke-width':2},rotor);const t=el('text',{'text-anchor':'middle',y:5,fill:'#e9fbfc','font-size':13},rotor);t.textContent='M';}else{el('circle',{r,fill:selected===c.id?'#17434a':'#18232d',stroke:'#91a9ba','stroke-width':3},rotor);el('line',{x1:-r-8,y1:0,x2:r+8,y2:0,stroke:'#91a9ba','stroke-width':4},rotor);}
    if(!['shaft','rack','crankSlider','camFollower'].includes(c.type))el('line',{x1:0,y1:0,x2:r*.8,y2:0,stroke:c.type==='motor'?'#a9e4e5':'#19b6bd','stroke-width':2.5},rotor);if(!['rack','crankSlider','camFollower'].includes(c.type))el('circle',{r:4,fill:'#111922',stroke:'#91a9ba'},g);
    const box=labels.get(c.id),localX=box.x-visual.anchorX,localY=box.y-visual.anchorY,annotation=el('g',{class:'annotation','pointer-events':'none'},g);el('rect',{class:'annotation-bg',x:localX,y:localY,width:box.width,height:box.height,rx:3},annotation);const label=el('text',{class:'label',x:localX+box.width/2,y:localY+8,'text-anchor':'middle'},annotation);label.textContent=visual.lines[0];const speed=el('text',{class:'speed-label',x:localX+box.width/2,y:localY+17,'text-anchor':'middle'},annotation);speed.textContent=visual.lines[1];
    this.nodes.set(c.id,{g,rotor:rackAnimation?.teeth||rotor,type:c.type,pitch:rackAnimation?.pitch,crank:crankAnimation,cam:camAnimation});
   }this.animate(angles);
  }
  animate(angles){for(const [id,n]of this.nodes){const position=angles.get(id)||0;if(n.type==='rack')n.rotor.setAttribute('transform',`translate(${((position%n.pitch)+n.pitch)%n.pitch} 0)`);else if(n.type==='crankSlider'){const phi=-position,r=n.crank.component.properties.crankRadius,pinX=r*Math.cos(phi),pinY=r*Math.sin(phi),sliderX=M.sliderPosition(n.crank.component,phi);n.rotor.setAttribute('transform',`rotate(${-position*180/Math.PI})`);for(const [key,value]of Object.entries({x1:pinX,y1:pinY,x2:sliderX,y2:0}))n.crank.rod.setAttribute(key,value);n.crank.slider.setAttribute('transform',`translate(${sliderX} 0)`);}else if(n.type==='camFollower'){const c=n.cam.component,phi=-position,followerY=c.properties.eccentricity*Math.sin(phi)-c.properties.baseRadius-5;n.rotor.setAttribute('transform',`rotate(${-position*180/Math.PI})`);n.cam.follower.setAttribute('transform',`translate(0 ${followerY})`);}else n.rotor.setAttribute('transform',`rotate(${-position*180/Math.PI})`);}for(const belt of this.belts)belt.line.setAttribute('stroke-dashoffset',String((angles.get(belt.id)||0)*8*belt.direction));}
 }
 root.ThosMotion.renderer={Renderer,phases,layoutAnnotations};
 if(typeof module!=='undefined')module.exports={Renderer,phases,layoutAnnotations};
})(globalThis);
