(function(root){
 'use strict';const M=root.ThosMotion.model,NS='http://www.w3.org/2000/svg';
 const el=(tag,attrs={},parent)=>{const n=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(parent)parent.append(n);return n;};
 function gearPath(c){const z=c.properties.teeth,r=M.radius(c),m=c.properties.module;let d='';for(let i=0;i<z*4;i++){const a=(i+.5)*Math.PI*2/(z*4),rr=i%4===0||i%4===3?r-m*.8:r+m*.8;d+=`${i?'L':'M'}${rr*Math.cos(a)},${rr*Math.sin(a)} `;}return d+'Z';}
 function phases(p){const out=new Map(),map=new Map(p.components.map(c=>[c.id,c]));for(const source of [...p.components.filter(c=>c.type==='motor'),...p.components]){if(out.has(source.id))continue;out.set(source.id,source.rotation);const queue=[source.id];for(let i=0;i<queue.length;i++){const a=map.get(queue[i]);for(const e of p.connections){const id=e.a===a.id?e.b:e.b===a.id?e.a:null;if(!id||out.has(id))continue;const b=map.get(id);if(!b)continue;const r=root.ThosMotion.connections.relation(a,b),valid=e.type==='belt'?a.type==='pulley'&&b.type==='pulley':r.state==='VALID_CONTACT';if(!valid)continue;let angle=out.get(a.id);if(e.type==='mesh'){const phi=Math.atan2(-(b.position.y-a.position.y),b.position.x-a.position.x);angle=((a.properties.teeth+b.properties.teeth)*phi+Math.PI*b.properties.teeth-Math.PI-a.properties.teeth*angle)/b.properties.teeth;}else if(e.type==='belt')angle*=root.ThosMotion.connections.ratio(e,a,b);out.set(id,angle);queue.push(id);}}}return out;}
 function beltLines(a,b,crossed){const dx=b.position.x-a.position.x,dy=b.position.y-a.position.y,d=Math.hypot(dx,dy)||1,px=-dy/d,py=dx/d,ra=M.radius(a),rb=M.radius(b),sign=crossed?-1:1;return [[a.position.x+px*ra,a.position.y+py*ra,b.position.x+px*rb*sign,b.position.y+py*rb*sign],[a.position.x-px*ra,a.position.y-py*ra,b.position.x-px*rb*sign,b.position.y-py*rb*sign]];}
 class Renderer{
  constructor(world){this.world=world;this.nodes=new Map();this.belts=[];}
  rebuild(p,selected,solution,angles){this.world.replaceChildren();this.nodes.clear();this.belts=[];const map=new Map(p.components.map(c=>[c.id,c]));for(const e of p.connections){const a=map.get(e.a),b=map.get(e.b);if(!a||!b)continue;if(e.type==='belt'){for(const [x1,y1,x2,y2]of beltLines(a,b,e.crossed)){const line=el('line',{x1,y1,x2,y2,stroke:'#7f95a6','stroke-width':4,'stroke-linecap':'round','stroke-dasharray':'5 3'},this.world);this.belts.push({line,id:e.a,direction:e.crossed?-1:1});}}else el('line',{x1:a.position.x,y1:a.position.y,x2:b.position.x,y2:b.position.y,stroke:'#526b7c','stroke-width':e.type==='shaft'?5:1.5,'stroke-dasharray':e.type==='mesh'?'3 4':'none'},this.world);}
   for(const c of p.components){const r=M.radius(c),s=solution.states.get(c.id);const mount=c.type==='motor'?p.connections.find(e=>e.type==='shaft'&&(e.a===c.id||e.b===c.id)):null;const partner=mount?map.get(mount.a===c.id?mount.b:mount.a):null;const offset=partner?-(M.radius(partner)+45):0;if(offset)el('line',{x1:c.position.x,y1:c.position.y,x2:c.position.x+offset,y2:c.position.y,stroke:'#087c87','stroke-width':2,'stroke-dasharray':'3 3'},this.world);const g=el('g',{'data-id':c.id,class:'component',tabindex:0,role:'button','aria-label':M.library[c.type].label,transform:`translate(${c.position.x+offset} ${c.position.y})`},this.world);
    el('circle',{r:r+7,fill:'transparent',stroke:selected===c.id?'#087c87':s.conflict?'#b54238':'transparent','stroke-width':2,class:'halo'},g);
    const rotor=el('g',{},g);if(c.type==='gear'){el('path',{d:gearPath(c),fill:selected===c.id?'#17434a':'#273643',stroke:'#91a9ba','stroke-width':1},rotor);el('circle',{r,fill:'none',stroke:'#5e7485','stroke-width':.6,'stroke-dasharray':'2 3'},rotor);}else if(c.type==='pulley'){el('circle',{r,fill:selected===c.id?'#17434a':'#202d38',stroke:'#91a9ba','stroke-width':3},rotor);el('circle',{r:r-5,fill:'none',stroke:'#657d8e','stroke-width':2},rotor);for(let i=0;i<4;i++)el('line',{x1:5,y1:0,x2:r-6,y2:0,stroke:'#71889a','stroke-width':2,transform:`rotate(${i*90})`},rotor);}else if(c.type==='motor'){el('circle',{r,fill:'#087c87',stroke:'#00a8ad','stroke-width':2},rotor);const t=el('text',{'text-anchor':'middle',y:5,fill:'#e9fbfc','font-size':13},rotor);t.textContent='M';}else{el('circle',{r,fill:selected===c.id?'#17434a':'#18232d',stroke:'#91a9ba','stroke-width':3},rotor);el('line',{x1:-r-8,y1:0,x2:r+8,y2:0,stroke:'#91a9ba','stroke-width':4},rotor);}
    if(c.type!=='shaft')el('line',{x1:0,y1:0,x2:r*.8,y2:0,stroke:c.type==='motor'?'#a9e4e5':'#19b6bd','stroke-width':2.5},rotor);el('circle',{r:4,fill:'#111922',stroke:'#91a9ba'},g);
    const label=el('text',{class:'label',y:r+10,'text-anchor':'middle'},g);label.textContent=c.type==='gear'?`Z${c.properties.teeth}`:c.type==='pulley'?`Ø${c.properties.diameter}`:M.library[c.type].label;const speed=el('text',{class:'speed-label',y:r+19,'text-anchor':'middle'},g);speed.textContent=`${s.rpm.toLocaleString('ca',{maximumFractionDigits:1})} rpm`;
    this.nodes.set(c.id,{g,rotor});
   }this.animate(angles);
  }
  animate(angles){for(const [id,n]of this.nodes)n.rotor.setAttribute('transform',`rotate(${-(angles.get(id)||0)*180/Math.PI})`);for(const belt of this.belts)belt.line.setAttribute('stroke-dashoffset',String((angles.get(belt.id)||0)*8*belt.direction));}
 }
 root.ThosMotion.renderer={Renderer,phases};
})(globalThis);
