const test=require('node:test'),assert=require('node:assert/strict');
const M=require('./model.js'),C=require('./connections.js'),{solve}=require('./solver.js');
const {layoutAnnotations,phases}=require('./renderer.js');
function pair(z1=20,z2=40,rpm=120){const p=M.empty(),m=M.create('motor',0,0),a=M.create('gear',0,0),b=M.create('gear',z1+z2,0);m.properties.rpm=rpm;a.properties.teeth=z1;b.properties.teeth=z2;p.components=[m,a,b];C.snap(p,a);C.snap(p,b);return {p,m,a,b};}
test('1:1, reducció i multiplicació amb inversió',()=>{for(const [z1,z2,n]of [[20,20,-100],[20,40,-50],[40,20,-200]]){const {p,b}=pair(z1,z2,100);assert.equal(solve(p).states.get(b.id).rpm,n);}});
test('120 → 120 → −60; mateix eix',()=>{const {p,m,a,b}=pair();const s=solve(p);assert.equal(s.states.get(m.id).rpm,120);assert.equal(s.states.get(a.id).rpm,120);assert.equal(s.states.get(b.id).rpm,-60);});
test('separació, eliminació i canvi de dents invaliden contactes',()=>{for(const kind of ['move','delete','teeth']){const {p,b}=pair();if(kind==='move')b.position.x+=20;if(kind==='delete')p.components=p.components.filter(c=>c!==b);if(kind==='teeth')b.properties.teeth=30;C.revalidate(p);assert.equal(p.connections.length,1);if(kind!=='delete')assert.equal(solve(p).states.get(b.id).rpm,0);}});
test('mòduls incompatibles i snap des de lluny',()=>{const {p,a,b}=pair();p.connections=[];b.properties.module=3;C.snap(p,b);assert.equal(C.relation(a,b).state,'INCOMPATIBLE');assert.equal(p.connections.length,0);b.properties.module=2;b.position.x=200;C.snap(p,b);assert.equal(p.connections.length,0);});
test('dos motors contradictoris bloquegen només el seu conjunt',()=>{const {p,b}=pair(),m=M.create('motor',b.position.x,0);m.properties.rpm=90;p.components.push(m);C.snap(p,m);const isolated=M.create('motor',200,200);p.components.push(isolated);const s=solve(p);assert.ok(s.states.get(b.id).conflict);assert.equal(s.states.get(b.id).rpm,0);assert.equal(s.states.get(isolated.id).rpm,120);});
test('cicle de tres engranatges no entra en bucle i detecta bloqueig',()=>{const p=M.empty(),m=M.create('motor',0,0),a=M.create('gear',0,0),b=M.create('gear',40,0),c=M.create('gear',20,Math.sqrt(1200));p.components=[m,a,b,c];C.snap(p,a);C.snap(p,b);C.snap(p,c);assert.ok(solve(p).diagnostics.some(d=>d.kind==='CONFLICT'));});
test('motor inactiu i velocitat negativa',()=>{const {p,m,b}=pair();m.properties.active=false;assert.equal(solve(p).states.get(b.id).rpm,0);m.properties.active=true;m.properties.rpm=-120;assert.equal(solve(p).states.get(b.id).rpm,60);});
test('persistència validada i rebuig de JSON malformat',()=>{const {p}=pair();assert.deepEqual(M.validate(JSON.parse(JSON.stringify(p))),p);for(const change of [p=>p.version=99,p=>p.components[0].properties.rpm=Infinity,p=>p.components[1].properties.teeth=0,p=>p.components[0].position.x='0',p=>p.components[1].id=p.components[0].id,p=>p.connections[0].b='missing',p=>p.components[0].type='__proto__']){const q=structuredClone(p);change(q);assert.throws(()=>M.validate(q));}});
test('un eix explícit transmet la mateixa velocitat a diversos components',()=>{const p=M.empty(),m=M.create('motor',0,0),shaft=M.create('shaft',0,0),g1=M.create('gear',0,0),g2=M.create('gear',0,0);p.components=[m,shaft,g1,g2];for(const c of p.components)C.snap(p,c);const s=solve(p);for(const c of p.components)assert.equal(s.states.get(c.id).rpm,120);assert.ok(p.connections.some(e=>e.type==='shaft'&&(e.a===shaft.id||e.b===shaft.id)));});
test('tren compost amb eixos: 100 → -50 → -50 → 10 rpm',()=>{const p=M.empty(),m=M.create('motor',0,0),sa=M.create('shaft',0,0),g1=M.create('gear',0,0),sb=M.create('shaft',60,0),g2=M.create('gear',60,0),g3=M.create('gear',60,0),sc=M.create('shaft',120,0),g4=M.create('gear',120,0);m.properties.rpm=100;g1.properties.teeth=20;g2.properties.teeth=40;g3.properties.teeth=10;g4.properties.teeth=50;p.components=[m,sa,g1,sb,g2,g3,sc,g4];for(const c of p.components)C.snap(p,c);const s=solve(p);assert.equal(s.states.get(g2.id).rpm,-50);assert.equal(s.states.get(g3.id).rpm,-50);assert.equal(s.states.get(g4.id).rpm,10);assert.equal(s.diagnostics.filter(d=>d.kind==='CONFLICT').length,0);});
test('la càrrega rebutja unions d’eix incompatibles',()=>{const p=M.empty(),a=M.create('shaft',0,0),b=M.create('shaft',0,0);p.components=[a,b];p.connections=[{id:'bad',type:'shaft',a:a.id,b:b.id}];assert.throws(()=>M.validate(p));});
function manualTrain(rotation=0){const p=M.empty(),a=M.create('gear',0,0),crank=M.create('manualCrank',0,0),b=M.create('gear',60,0);crank.rotation=rotation;b.properties.teeth=40;p.components=[a,crank,b];C.snap(p,crank);C.snap(p,b);return {p,a,crank,b};}
test('la manovella manual transmet l’angle pel tren i la cremallera sense activar velocitat',()=>{const zero=manualTrain(0),turned=manualTrain(1),p0=phases(zero.p),p1=phases(turned.p),s=solve(turned.p);assert.ok(Math.abs((p1.get(turned.b.id)-p0.get(zero.b.id))+.5)<1e-9);assert.equal(s.states.get(turned.b.id).rpm,0);assert.equal(s.diagnostics.some(d=>d.kind==='WARNING'),false);const rack=M.create('rack',0,20);turned.p.components.push(rack);C.snap(turned.p,rack);assert.ok(Math.abs(phases(turned.p).get(rack.id)-20)<1e-9);});
test('persistència validada de la manovella manual',()=>{const {p,crank}=manualTrain(.75),copy=M.validate(JSON.parse(JSON.stringify(p)));assert.equal(copy.components.find(c=>c.id===crank.id).properties.radius,28);assert.equal(copy.components.find(c=>c.id===crank.id).rotation,.75);const bad=structuredClone(p);bad.components.find(c=>c.id===crank.id).properties.radius=5;assert.throws(()=>M.validate(bad));});
test('el suport es fixa per contacte coaxial i es desconnecta en separar-lo',()=>{const p=M.empty(),shaft=M.create('shaft',0,0),support=M.create('support',0,0);p.components=[shaft,support];C.snap(p,support);assert.equal(p.connections.find(e=>e.type==='support')?.a,support.id);support.position.x=2;C.revalidate(p);assert.equal(p.connections.some(e=>e.type==='support'),false);});
test('el suport és estructural, no transmet moviment i es conserva al projecte',()=>{const p=M.empty(),motor=M.create('motor',0,0),a=M.create('gear',0,0),support=M.create('support',0,0),b=M.create('gear',0,0);p.components=[motor,a,support,b];C.snap(p,a);p.connections.push({id:crypto.randomUUID(),type:'support',a:support.id,b:b.id});const s=solve(p),copy=M.validate(JSON.parse(JSON.stringify(p)));assert.equal(s.states.get(a.id).rpm,120);assert.equal(s.states.get(b.id).rpm,0);assert.equal(s.states.get(support.id).rpm,0);assert.equal(copy.connections.filter(e=>e.type==='support').length,2);const bad=structuredClone(p),edge=bad.connections.find(e=>e.type==='support');edge.a=motor.id;edge.b=support.id;assert.throws(()=>M.validate(bad));});
function pulleys(crossed=false){const p=M.empty(),m=M.create('motor',0,0),a=M.create('pulley',0,0),b=M.create('pulley',130,0);a.properties.diameter=80;b.properties.diameter=40;p.components=[m,a,b];C.snap(p,m);p.connections.push({id:crypto.randomUUID(),type:'belt',a:a.id,b:b.id,crossed});return {p,m,a,b};}
test('corretja oberta: mateix sentit i relació de diàmetres',()=>{const {p,b}=pulleys(false),s=solve(p);assert.equal(s.states.get(b.id).rpm,240);assert.equal(s.states.get(b.id).ratio,2);});
test('corretja creuada: sentit contrari i relació de diàmetres',()=>{const {p,b}=pulleys(true),s=solve(p);assert.equal(s.states.get(b.id).rpm,-240);assert.equal(s.states.get(b.id).ratio,-2);});
test('la corretja es conserva en moure politges i cau si se superposen',()=>{const {p,b}=pulleys();b.position.y=80;C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='belt').length,1);b.position={x:20,y:0};C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='belt').length,0);});
test('persistència de corretges i rebuig de paràmetres invàlids',()=>{const {p}=pulleys(true),copy=M.validate(JSON.parse(JSON.stringify(p)));assert.equal(copy.connections.find(e=>e.type==='belt').crossed,true);const bad=structuredClone(p);bad.connections.find(e=>e.type==='belt').crossed='sí';assert.throws(()=>M.validate(bad));});
function frictionDrive(d1=40,d2=80){const p=M.empty(),m=M.create('motor',0,0),a=M.create('frictionWheel',0,0),b=M.create('frictionWheel',(d1+d2)/2,0);m.properties.rpm=120;a.properties.diameter=d1;b.properties.diameter=d2;p.components=[m,a,b];C.snap(p,a);C.snap(p,b);return {p,m,a,b};}
test('rodes de fricció: sentit contrari i relació de diàmetres',()=>{for(const [d1,d2,rpm]of [[40,80,-60],[80,40,-240],[50,50,-120]]){const {p,b}=frictionDrive(d1,d2),s=solve(p);assert.equal(s.states.get(b.id).rpm,rpm);assert.equal(s.states.get(b.id).ratio,-d1/d2);}});
test('les rodes de fricció es desconnecten en separar-se o interferir',()=>{const {p,a,b}=frictionDrive();assert.equal(p.connections.filter(e=>e.type==='friction').length,1);b.position.x+=10;C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='friction').length,0);b.position={x:M.radius(a)+M.radius(b)-1,y:0};p.connections.push({id:crypto.randomUUID(),type:'friction',a:a.id,b:b.id});C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='friction').length,0);});
test('persistència validada de les rodes de fricció',()=>{const {p,b}=frictionDrive(),copy=M.validate(JSON.parse(JSON.stringify(p)));assert.equal(copy.components.find(c=>c.id===b.id).properties.diameter,80);assert.equal(copy.connections.find(e=>e.type==='friction').type,'friction');const bad=structuredClone(p);bad.components.find(c=>c.id===b.id).properties.diameter=5;assert.throws(()=>M.validate(bad));});
function chainDrive(z1=16,z2=32){const p=M.empty(),m=M.create('motor',0,0),a=M.create('sprocket',0,0),b=M.create('sprocket',160,0);m.properties.rpm=60;a.properties.teeth=z1;b.properties.teeth=z2;p.components=[m,a,b];C.snap(p,a);p.connections.push({id:crypto.randomUUID(),type:'chain',a:a.id,b:b.id});return {p,m,a,b};}
test('cadena: mateix sentit i relació del nombre de dents',()=>{for(const [z1,z2,n]of [[16,32,30],[32,16,120],[20,20,60]]){const {p,b}=chainDrive(z1,z2),s=solve(p);assert.equal(s.states.get(b.id).rpm,n);assert.equal(s.states.get(b.id).ratio,z1/z2);}});
test('la cadena es conserva en moure pinyons i cau si se superposen o canvia el pas',()=>{const {p,a,b}=chainDrive();b.position.y=70;C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='chain').length,1);b.position={x:M.radius(a)+M.radius(b)-1,y:0};C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='chain').length,0);p.connections.push({id:crypto.randomUUID(),type:'chain',a:a.id,b:b.id});b.position={x:160,y:0};b.properties.pitch=10;C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='chain').length,0);});
test('persistència validada de pinyons i cadena',()=>{const {p,b}=chainDrive(),copy=M.validate(JSON.parse(JSON.stringify(p)));assert.equal(copy.components.find(c=>c.id===b.id).properties.teeth,32);assert.equal(copy.connections.find(e=>e.type==='chain').type,'chain');for(const change of [q=>q.components.find(c=>c.id===b.id).properties.teeth=0,q=>q.components.find(c=>c.id===b.id).properties.pitch=30,q=>q.components.find(c=>c.id===b.id).properties.pitch=10]){const bad=structuredClone(p);change(bad);assert.throws(()=>M.validate(bad));}});
function wormDrive(starts=1,teeth=30){const p=M.empty(),m=M.create('motor',0,0),worm=M.create('worm',0,0),wheel=M.create('wormWheel',100,0);m.properties.rpm=120;worm.properties.starts=starts;wheel.properties.teeth=teeth;p.components=[m,worm,wheel];C.snap(p,worm);p.connections.push({id:crypto.randomUUID(),type:'worm',a:worm.id,b:wheel.id});return {p,m,worm,wheel};}
test('cargol sense fi: la corona redueix segons entrades i dents',()=>{for(const [starts,teeth,rpm]of [[1,30,4],[2,30,8],[4,60,8]]){const {p,wheel}=wormDrive(starts,teeth),s=solve(p);assert.equal(s.states.get(wheel.id).rpm,rpm);assert.equal(s.states.get(wheel.id).ratio,starts/teeth);}});
test('el cargol i la corona exigeixen el mateix mòdul',()=>{const {p,worm,wheel}=wormDrive();wheel.position.y=70;C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='worm').length,1);wheel.properties.module=3;C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='worm').length,0);wheel.properties.module=2;wheel.position={...worm.position};p.connections.push({id:crypto.randomUUID(),type:'worm',a:worm.id,b:wheel.id});C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='worm').length,0);});
test('persistència validada del cargol sense fi i la corona',()=>{const {p,worm,wheel}=wormDrive(),copy=M.validate(JSON.parse(JSON.stringify(p)));assert.equal(copy.components.find(c=>c.id===worm.id).properties.starts,1);assert.equal(copy.components.find(c=>c.id===wheel.id).properties.teeth,30);assert.equal(copy.connections.find(e=>e.type==='worm').type,'worm');for(const change of [q=>q.components.find(c=>c.id===worm.id).properties.starts=0,q=>q.components.find(c=>c.id===wheel.id).properties.teeth=8,q=>q.components.find(c=>c.id===wheel.id).properties.module=3]){const bad=structuredClone(p);change(bad);assert.throws(()=>M.validate(bad));}});
function rackDrive(side=1){const p=M.empty(),m=M.create('motor',0,0),g=M.create('gear',0,0),rack=M.create('rack',0,side*20);m.properties.rpm=60;p.components=[m,g,rack];C.snap(p,g);C.snap(p,rack);return {p,m,g,rack};}
test('pinyó-cremallera: v = ωr i sentit segons el costat de contacte',()=>{for(const side of [1,-1]){const {p,rack}=rackDrive(side),s=solve(p).states.get(rack.id);assert.equal(s.motion,'linear');assert.ok(Math.abs(s.linearSpeed-side*40*Math.PI)<1e-9);}});
test('la cremallera se separa, rebutja un mòdul incompatible i queda aturada',()=>{const {p,g,rack}=rackDrive();rack.position.y+=20;C.revalidate(p);assert.equal(p.connections.filter(e=>e.type==='rack').length,0);rack.position.y=20;rack.properties.module=3;C.snap(p,rack);assert.equal(C.relation(g,rack).state,'INCOMPATIBLE');assert.equal(solve(p).states.get(rack.id).linearSpeed,0);});
test('persistència validada del pinyó-cremallera',()=>{const {p,rack}=rackDrive(),copy=M.validate(JSON.parse(JSON.stringify(p)));assert.equal(copy.components.find(c=>c.id===rack.id).properties.teeth,24);assert.equal(copy.connections.find(e=>e.type==='rack').type,'rack');const bad=structuredClone(p);bad.components.find(c=>c.id===rack.id).properties.teeth=0;assert.throws(()=>M.validate(bad));});
test('un conflicte també atura la velocitat lineal',()=>{const {p,g,rack}=rackDrive(),m2=M.create('motor',0,0);m2.properties.rpm=30;p.components.push(m2);C.snap(p,m2);const s=solve(p);assert.equal(s.states.get(g.id).rpm,0);assert.equal(s.states.get(rack.id).linearSpeed,0);assert.equal(s.states.get(rack.id).conflict,true);});
test('les etiquetes busquen espai lliure sense tapar components ni altres dades',()=>{const items=[{id:'a',x:0,y:0,halfWidth:22,halfHeight:22,lines:['Z20','120 rpm']},{id:'b',x:44,y:0,halfWidth:22,halfHeight:22,lines:['Z20','-120 rpm']},{id:'c',x:22,y:22,halfWidth:70,halfHeight:5,lines:['Z24 · m2','125,7 mm/s']}],labels=layoutAnnotations(items),boxes=[...labels.values()],overlap=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)assert.equal(overlap(boxes[i],boxes[j]),false);for(const item of items){const own=labels.get(item.id);for(const other of items.filter(x=>x.id!==item.id)){const component={x:other.x-other.halfWidth,y:other.y-other.halfHeight,width:other.halfWidth*2,height:other.halfHeight*2};assert.equal(overlap(own,component),false);}}});
test('biela-manovella: la cursa de la corredera és dues vegades el radi',()=>{const c=M.create('crankSlider',0,0),outer=M.sliderDisplacement(c,0),inner=M.sliderDisplacement(c,Math.PI);assert.ok(Math.abs(outer-inner-2*c.properties.crankRadius)<1e-9);assert.ok(M.sliderPosition(c,Math.PI/2)>0);});
test('la biela-manovella rep la velocitat del motor pel mateix eix',()=>{const p=M.empty(),m=M.create('motor',0,0),c=M.create('crankSlider',0,0);m.properties.rpm=30;p.components=[m,c];C.snap(p,c);assert.equal(p.connections[0].type,'shaft');assert.equal(solve(p).states.get(c.id).rpm,30);});
test('persistència i dimensions vàlides de la biela-manovella',()=>{const p=M.empty(),c=M.create('crankSlider',0,0);p.components=[c];assert.deepEqual(M.validate(JSON.parse(JSON.stringify(p))).components[0].properties,c.properties);for(const change of [x=>x.crankRadius=0,x=>x.rodLength=x.crankRadius]){const bad=structuredClone(p);change(bad.components[0].properties);assert.throws(()=>M.validate(bad));}});
test('lleva-seguidor: l’alçament total és dues vegades l’excentricitat',()=>{const c=M.create('camFollower',0,0),low=M.camLift(c,-Math.PI/2),high=M.camLift(c,Math.PI/2);assert.ok(Math.abs(low)<1e-9);assert.ok(Math.abs(high-2*c.properties.eccentricity)<1e-9);});
test('la lleva-seguidor rep la velocitat del motor pel mateix eix',()=>{const p=M.empty(),m=M.create('motor',0,0),c=M.create('camFollower',0,0);m.properties.rpm=45;p.components=[m,c];C.snap(p,c);assert.equal(p.connections[0].type,'shaft');assert.equal(solve(p).states.get(c.id).rpm,45);});
test('persistència i dimensions vàlides de la lleva-seguidor',()=>{const p=M.empty(),c=M.create('camFollower',0,0);p.components=[c];assert.deepEqual(M.validate(JSON.parse(JSON.stringify(p))).components[0].properties,c.properties);for(const change of [x=>x.baseRadius=0,x=>x.eccentricity=x.baseRadius+1]){const bad=structuredClone(p);change(bad.components[0].properties);assert.throws(()=>M.validate(bad));}});
test('el velocímetre de la biela-manovella coincideix amb la derivada de la posició',()=>{const c=M.create('crankSlider',0,0),angle=.7,omega=2.3,h=1e-6,numeric=(M.sliderPosition(c,angle+h)-M.sliderPosition(c,angle-h))/(2*h)*omega;assert.ok(Math.abs(M.sliderVelocity(c,angle,omega)-numeric)<1e-6);});
test('el velocímetre del seguidor coincideix amb la derivada de l’alçament',()=>{const c=M.create('camFollower',0,0),angle=.4,omega=1.7,h=1e-6,numeric=(M.camLift(c,-(angle+h))-M.camLift(c,-(angle-h)))/(2*h)*omega;assert.ok(Math.abs(M.camLiftVelocity(c,angle,omega)-numeric)<1e-6);});
